name: Build Gatsby Static Server

on:
  push:
    branches:
      - master
    tags:
      - "gatsby-static-server*"
    paths:
      - "gatsby-static-server/**"
      - ".github/workflows/build-gatsby-static-server.yml"

jobs:
  test:
    name: Test Nginx settings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: make gatsby-static-server-test
  build:
    needs: ["test"]
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_TOOLS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_TOOLS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Print AWS Caller Identity
        run: aws sts get-caller-identity
      - name: Set image tag
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/*/}
          IMAGE_TAG=${IMAGE_TAG#gatsby-static-server-}
          if [[ $IMAGE_TAG == "master" ]]
          then
            IMAGE_TAG="latest"
          fi
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
      - name: Login to Public ECR
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u7h7z7i1
      - name: Build image
        run: make gatsby-static-server-build TAG=${IMAGE_TAG}
      - name: Push docker image
        run: make gatsby-static-server-push TAG=${IMAGE_TAG}
